# Generated by Django 4.2 on 2023-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
